# Generated by Django 5.1.4 on 2025-03-15 21:44

from django.db import migrations, models
from src.core.shared.enums import Status


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0004_user_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="status",
            field=models.CharField(
                choices=Status.choices(),
                default=Status.ACTIVE.value,
                max_length=255,
            ),
        ),
    ]
