# Generated by Django 5.1.4 on 2025-03-15 21:44

import src.core.utils.enums
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'ACTIVE'), ('INACTIVE', 'INACTIVE')], default=src.core.utils.enums.Status['ACTIVE'], max_length=255),
        ),
    ]
