# Generated by Django 5.1.7 on 2025-03-26 03:08

import src.core.shared.enums
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_user_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'ACTIVE'), ('INACTIVE', 'INACTIVE'), ('PENDING', 'PENDING')], default=src.core.shared.enums.Status['ACTIVE'], max_length=255),
        ),
    ]
