# Generated by Django 5.1.7 on 2025-03-27 02:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django', '0001_initial'),
        ('store', '0007_alter_store_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='store',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='store.store'),
            preserve_default=False,
        ),
    ]
