# Generated by Django 5.1.7 on 2025-03-29 20:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django', '0002_category_store'),
        ('store', '0007_alter_store_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='size',
            name='store',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='store.store'),
            preserve_default=False,
        ),
    ]
