# Generated by Django 5.1.4 on 2025-03-04 18:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='store_hours',
            field=models.ManyToManyField(related_name='stores', to='store.storehour'),
        ),
        migrations.AddField(
            model_name='storehour',
            name='store',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='hours', to='store.store'),
            preserve_default=False,
        ),
    ]
