# Generated by Django 5.1.4 on 2025-03-05 18:38

import src.core.store.domain.entity
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_alter_store_id_alter_store_owner_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='status',
            field=models.CharField(choices=src.core.store.domain.entity.StoreStatus.choices, default=src.core.store.domain.entity.StoreStatus['ACTIVE'], max_length=255),
        ),
    ]
