# Generated by Django 5.1.4 on 2025-03-04 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_store_store_hours_storehour_store'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='store_hours',
        ),
        migrations.DeleteModel(
            name='StoreHour',
        ),
    ]
