# Generated by Django 5.1.4 on 2025-03-04 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_remove_store_store_hours_delete_storehour'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='business_hours',
            field=models.JSONField(default=None),
            preserve_default=False,
        ),
    ]
