# Generated by Django 5.1.4 on 2025-03-05 18:38

from django.db import migrations, models
from src.core.shared.enums import Status


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0005_alter_store_id_alter_store_owner_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="store",
            name="status",
            field=models.CharField(
                choices=Status.choices,
                default=Status.ACTIVE.value,
                max_length=255,
            ),
        ),
    ]
