# Generated by Django 5.1.7 on 2025-03-26 03:08

import src.core.shared.enums
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_store_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='status',
            field=models.CharField(choices=src.core.shared.enums.Status.choices, default=src.core.shared.enums.Status['ACTIVE'], max_length=255),
        ),
    ]
